### ISSUE TITLE
Implement in-memory only version of JuicyPotato

### ISSUE THREAD

**Issue by phra** [antonioCoco/SharPyShell#1]
Nice project!

It would be nice to have an in-memory only version of JuicyPotato exploit using Reflective DLL Injection.

You can check here how to compile a working reflective injectable dll version of it: https://github.com/rapid7/metasploit-framework/pull/11230

**Comment by antonioCoco** [comment]
Thank you!
I was looking around how to do that.
I didn't know that module of metasploit, i will give it a check and see if i can integrate.
When i tried to implement it i was looking to find a way to load the .net assembly of the juicy potato as a bytearray, but no chance because it's compiled as native dll.

**Comment by phra** [comment]
@antonioCoco i wrote to you on linkedin, if you need any help just ping me :smiley:
