### ISSUE TITLE
Operation did not complete successfully because the file contains a virus or potentially unwanted software

### ISSUE THREAD

**Issue by rahamoosavi1378** [antonioCoco/SharPyShell#23]
[redacted]

`Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4110.0`

**Comment by antonioCoco** [comment]
Some AV is blocking your shell through the AMSI provider interface. 
So try to disable the AV on the testing machine or develop a way to evade it by yourself.

Moreover, when you upload the screenshot for troubleshooting be careful in redacting the information about the target you are trying to exploit. I have redacted the image because it could have potentially harmed your customer. 
I'm saying "your customer" because, looking at the target domain, i really hope you got an agreement for your testing. 
Otherwise, you are doing illegal activities against gov orgs.
